### ISSUE TITLE
Undefined Variable: provider

### ISSUE THREAD

**Issue by GrnPero** [savanihd/paypal-payment-gateway-integration-in-laravel-5.8#2]
Hello, I seem to be getting an error message after I go through the payment screen for paypal.
![Code](https://user-images.githubusercontent.com/44035269/76650089-23f6f480-651f-11ea-8f90-4ce2a1557425.PNG)
![Error](https://user-images.githubusercontent.com/44035269/76650090-23f6f480-651f-11ea-8755-febf981e5490.PNG)

**Comment by bngameni** [comment]
> Hello, I seem to be getting an error message after I go through the payment screen for paypal.
> ![Code](https://user-images.githubusercontent.com/44035269/76650089-23f6f480-651f-11ea-8f90-4ce2a1557425.PNG)
> ![Error](https://user-images.githubusercontent.com/44035269/76650090-23f6f480-651f-11ea-8755-febf981e5490.PNG)

Hey do you have solved this problem ??
Because, I have the same problem!!

In My success function, I have Instanciate, new ExpressCheckout to $provider for solve it!!

**Comment by tusharcoder** [comment]
I had same Issue: solved by instantiate new ExpressCheckout to $provider to solve it
